name: WorkflowTest

on:
  workflow_dispatch:

jobs:
  workflowtest1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get Brew Tap Parameters
      id: brew-tap
      run: |
        cat ./.brew-tap >> $GITHUB_OUTPUT
      env:
        GITHUB_OUTPUT: $GITHUB_OUTPUT

  workflowtest2:
    needs: [workflowtest1]
    runs-on: ubuntu-latest

    steps:
      - name: Show vars
        run: |
          echo ${{ steps.brew-tap.outputs }}
