name: WorkflowTest

on:
  workflow_dispatch:

jobs:
  workflowtest1:
    runs-on: ubuntu-latest
    outputs:
      formula: ${{ steps.brew-tap.outputs.formula }}
      description: ${{ steps.brew-tap.outputs.description }}
      homepage: ${{ steps.brew-tap.outputs.homepage }}
      license: ${{ steps.brew-tap.outputs.license }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get Brew Tap Parameters
      id: brew-tap
      run: |
        cat ./.brew-tap >> $GITHUB_OUTPUT

  workflowtest2:
    needs: [workflowtest1]
    runs-on: ubuntu-latest

    steps:
      - name: Show vars
        run: |
          echo "${{ needs.workflowtest1.outputs.formula }}"
          echo "${{ needs.workflowtest1.outputs.description }}"
          echo "${{ needs.workflowtest1.outputs.homepage }}"
          echo "${{ needs.workflowtest1.outputs.license }}"
