name: Update Tap Repository

on:
  push:
    tags: ['*']
  release:
  workflow_dispatch:  # 手動実行を有効化する設定


jobs:
  update-tap:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download release asset
      run: |
        curl -L -s "${{ github.event.head_commit.url }}/archive/${{ github.ref }}.tar.gz" -o release.tar.gz

    - name: Calculate SHA256
      id: sha256
      run: echo "sha256=$(sha256sum release.tar.gz | awk '{ print $1 }')" >> $GITHUB_OUTPUT

    - name: Clone tap repository
      uses: actions/checkout@v2
      with:
        repository: aromarious/homebrew-private
        path: homebrew-private

    - name: Set formula name
      id: formula
      run: echo "formula=$(echo ${{ github.repository }} | cut -d / -f 2)" >> $GITHUB_OUTPUT

    - name: Update formula
      run: |
        cd homebrew-private
        sed -i.bak 's/sha256 "[a-f0-9]\{64\}"/sha256 "${{ steps.sha256.outputs.sha256 }}"/' "Formula/${{ steps.formula.outputs.formula }}.rb"

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update formula for new release on ${{ github.repository }} - ${{ github.event.release.tag_name }}"
        repository: homebrew-private
        file_pattern: Formula/${{ steps.formula.outputs.formula }}.rb
        branch: main
        commit_user_name: github-actions[bot]
        commit_user_email: github-actions[bot]@users.noreply.github.com
