name: Update version and create release

on:
  push:
    tags:
      - 'v*' # vで始まるタグが作成されたときに実行

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Create release archive
        run: |
          mkdir release
          cp -r dist bin package.json release/
          cd release
          tar czf ../display-rotate.tar.gz .

      - name: Generate SHA256
        run: |
          echo "SHA256=$(shasum -a 256 display-rotate.tar.gz | awk '{print $1}')" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: display-rotate.tar.gz
          body: |
            SHA256: ${{ env.SHA256 }}

            This release contains pre-built files for Homebrew installation.

      - name: Commit version update
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -am "chore: update version to ${{ github.ref_name }}"
          git push
