name: Update Tap Repository

on:
  push:
    tags: ['*']
  release:
  workflow_dispatch:  # 手動実行を有効化する設定


jobs:
  update-tap:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download release asset
      run: |
        curl -L "${{ github.event.head_commit.url }}/archive/${{ github.ref }}.tar.gz" -o release.tar.gz

    - name: Calculate SHA256
      id: sha256
      run: echo "::set-output name=sha256::$(sha256sum release.tar.gz | awk '{ print $1 }')"

    - name: Clone tap repository
      run: git clone https://github.com/aromarious/homebrew-private.git

    - name: Set formula name
      id: formula
      run: echo "::set-output name=formula::$(echo ${{ github.repository }} | cut -d / -f 2)"

    - name: Update formula
      run: |
        FORMULA_FILE="Formula/${{ steps.formula.outputs.formula }}.rb"
        cd homebrew-private
        sed -i.bak 's/sha256 "[a-f0-9]\{64\}"/sha256 "${{ steps.sha256.outputs.sha256 }}"/' $FORMULA_FILE

    - name: Commit and push changes
      run: |
        cd homebrew-private
        git add .
        git commit -m "Update formula for new release ${{ github.event.release.tag_name }}"
        git push origin main
