name: WorkflowTest

on:
  push:
    tags:
  release:
  workflow_dispatch:  # 手動実行を有効化する設定

jobs:
  workflowtest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Display GitHub context variables
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        SECRETS_CONTEXT: ${{ toJson(secrets) }}
      run: |
        echo "$GITHUB_CONTEXT"
        echo "$SECRETS_CONTEXT"
